---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 您可以将 ONTAP Select 映像添加到 Deploy 管理实用程序的实例中。安装映像后，您可以在部署 ONTAP Select 群集时使用它。 
---
= 将ONTAP Select映像添加到 Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以将 ONTAP Select 映像添加到 Deploy 管理实用程序的实例中。安装映像后，您可以在部署 ONTAP Select 群集时使用它。



== 开始之前

在高级别上，用于将 ONTAP Select 映像添加到 Deploy 实例的过程包括四个步骤：

. 下载安装映像
. 将安装映像上传到 Deploy 虚拟机
. 添加安装映像
. 显示可用的安装映像


在将任何新的ONTAP Select映像添加到 Deploy 之前，您应该先删除所有不需要的映像。


NOTE: 您只能添加版本低于 Deploy 实用程序实例所含原始版本的ONTAP Select映像。不支持添加NetApp提供的ONTAP Select更高版本。



== 下载安装映像

要开始将ONTAP Select映像添加到 Deploy 实用程序实例，您必须从NetApp支持站点下载安装映像。ONTAPONTAP Select安装映像的格式为单个压缩文件。

.步骤
. 使用 Web 浏览器访问 NetApp 支持站点，然后单击*支持快速链接*。
. 单击 *热门任务* 下的 *下载软件* 并登录到该站点。
. 单击 *Find your product*。
. 向下滚动并单击 *ONTAP Select*。
. 在 *Other Available Select Software* 下单击 *Deploy Upgrade, Node Upgrade, Image Install*。
. 选择升级软件包的所需版本。
. 查看最终用户许可协议 (EULA)，然后单击 *Accept & Continue*。
. 选择并下载相应的软件包，根据您的环境需要响应所有提示。




== 将安装映像上传到 Deploy

获取ONTAP Select安装映像后，您必须将该文件上传到 Deploy 虚拟机。

.开始之前
您必须在本地工作站上具有可用的安装映像文件。您还必须有 Deploy 管理员用户帐户的密码。

.关于此任务
此任务描述了将文件上传到 Deploy 虚拟机的一种方法。可能还有其他更适合您环境的选项。

.步骤
. 在本地工作站上的命令 shell 中，将映像文件上传到 Deploy 虚拟机。
+
示例

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
示例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.结果
节点安装文件存储在管理员用户的主目录中。



== 添加安装映像

您可以将 ONTAP Select 安装映像添加到 Deploy images 目录，以便在部署新集群时可用。

.开始之前
您必须知道安装映像文件在 Deploy 实用程序虚拟机中的哪个目录中。假设该文件位于管理员的主目录中。

.步骤
. 使用管理员 (admin) 帐户通过 SSHSign in到 Deploy 实用程序 CLI。
. 启动 Bash shell：
+
`shell bash`

. 将安装映像文件放入 images 目录。
+
示例
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 显示可用的安装映像

您可以显示部署新集群时可用的 ONTAP Select 图像。

.步骤
. 访问部署实用程序虚拟机上的在线文档网页，并使用管理员 (admin) 帐户登录：
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
使用 Deploy 虚拟机的域名或 IP 地址。

. 导航到页面底部并单击 *Deploy*，然后单击 *GET /images*。
. 单击 *Try it out!* 以显示可用的 ONTAP Select 图像。
. 确认所需图像可用。

