---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果ONTAP Select Deploy 实用程序因某种原因发生故障或不可用，您将无法管理ONTAP Select节点和集群。此外，所有双节点集群都会失去 HA 功能，因为 Deploy 附带的调解器服务不可用。如果发生不可恢复的故障，您必须恢复 Deploy 实用程序实例才能恢复管理和 HA 功能。 
---
= 恢复双节点集群的ONTAP Select Deploy 实用程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果ONTAP Select Deploy 实用程序因某种原因发生故障或不可用，您将无法管理ONTAP Select节点和集群。此外，所有双节点集群都会失去 HA 功能，因为 Deploy 附带的调解器服务不可用。如果发生不可恢复的故障，您必须恢复 Deploy 实用程序实例才能恢复管理和 HA 功能。



== 开始之前

在尝试恢复 Deploy 实用程序实例之前，您应该做好准备以确保成功。

.所需技能和信息
您应该熟悉一些管理程序并掌握所需的信息。

.安装 Deploy 虚拟机
您必须能够在虚拟机管理程序环境中安装ONTAP Select Deploy 实用程序的新实例。

.ONTAP命令行界面
您必须能够登录到ONTAP Select集群的ONTAP CLI 并使用 shell 界面。

.部署实用程序配置备份的可用性
您必须确定是否拥有包含ONTAP Select双节点集群的故障 Deploy 实用程序实例的配置数据备份。您可能拥有不包含该集群的备份。

.恢复 Deploy 配置的备份
根据所使用的恢复程序，您应该能够恢复 Deploy 配置数据的备份。

.原始 Deploy 虚拟机的 IP 地址
您必须知道发生故障的原始 Deploy 实用程序虚拟机的 IP 地址。

.存储容量许可
您必须确定使用的是容量池许可还是容量层许可。如果使用容量池许可，则必须在恢复或还原 Deploy 实例后重新安装每个容量池许可证。

.决定使用哪种恢复程序
您必须决定在恢复ONTAP Select Deploy 实用程序实例时使用哪个步骤。您的决定取决于您是否拥有包含ONTAP Select双节点集群的原始故障 Deploy 实用程序的配置数据备份。

[cols="35,65"]
|===
| 您是否有包含双节点集群的 Deploy 备份？ | 要使用的恢复程序 


| 是 | 使用配置备份恢复 Deploy 实用程序实例 


| 否 | 重新配置并恢复 Deploy 实用程序实例 
|===


== 使用配置备份恢复 Deploy 实用程序实例

如果您拥有包含双节点集群的故障 Deploy 实用程序实例的备份，则可以将配置数据还原到新的 Deploy 虚拟机实例。然后，您必须通过对ONTAP Select集群中的两个节点执行额外的配置来完成恢复。

.开始之前
您必须拥有包含双节点集群的原始故障 Deploy 虚拟机的配置数据备份。您必须能够登录双节点集群的ONTAP CLI，并且知道这两个节点的ONTAP名称。

.关于此任务
由于您恢复的配置备份包含双节点集群，因此将在新的 Deploy 实用程序虚拟机中重新创建中介 iSCSI 目标和邮箱。

.步骤
. 准备ONTAP Select Deploy 实用程序的新实例：
+
.. 安装新的 Deploy 实用程序虚拟机。
.. 将 Deploy 配置从以前的备份恢复到新的虚拟机。
+
有关安装和恢复过程的更多详细信息，请参阅相关任务。



. Sign inONTAP Select双节点集群的ONTAP命令行界面。
. 进入高级权限模式：
+
`set adv`

. 如果新 Deploy 虚拟机的 IP 地址与原始 Deploy 虚拟机不同，则必须删除旧的中介 iSCSI 目标并添加新的目标：
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
这 `<ip_address>`参数是新的 Deploy 虚拟机的 IP 地址。

+
这些命令允许ONTAP Select节点发现新 Deploy 实用程序虚拟机上的邮箱磁盘。

. 确定中介磁盘的名称：
+
`disk show -container-type mediator`

. 将邮箱磁盘分配给两个节点：
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>
disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. 验证存储故障转移是否已启用：
+
`storage failover show`



.完成后
如果使用容量池许可，则必须重新安装每个容量池许可证。有关更多详细信息，请参阅“重新安装容量池许可证”。



== 重新配置并恢复 Deploy 实用程序实例

如果您没有包含双节点集群的故障 Deploy 实用程序实例的备份，则必须在新的 Deploy 虚拟机中配置调解器 iSCSI 目标和邮箱。然后，您必须通过对ONTAP Select集群中的两个节点执行额外配置来完成恢复。

.开始之前
您必须知道新 Deploy 实用程序实例的调解器目标的名称。您必须能够登录双节点集群的ONTAP CLI，并且知道这两个节点的ONTAP名称。

.关于此任务
即使新的 Deploy 虚拟机不包含双节点集群，您也可以选择将配置备份还原到该虚拟机。由于还原操作不会重新创建双节点集群，因此您必须通过 Deploy 上的ONTAP Select在线文档网页，手动将中介 iSCSI 目标和邮箱添加到新的 Deploy 实用程序实例。您必须能够登录双节点集群，并且知道这两个节点的ONTAP名称。


NOTE: 恢复过程的目标是将双节点集群恢复到健康状态，以便可以执行正常的 HA 接管和交还操作。

.步骤
. 准备ONTAP Select Deploy 实用程序的新实例：
+
.. 安装新的 Deploy 实用程序虚拟机。
.. 可以选择将 Deploy 配置从以前的备份恢复到新的虚拟机。
+
如果您恢复之前的备份，新的 Deploy 实例将不包含双节点集群。有关安装和恢复过程的更多详细信息，请参阅相关信息部分。



. Sign inONTAP Select双节点集群的ONTAP命令行界面。
. 进入高级特权模式：
+
`set adv`

. 获取中介 iSCSI 目标名称：
+
`storage iscsi-initiator show -target-type mailbox`

. 访问新部署实用程序虚拟机上的在线文档网页并使用管理员帐户登录：
+
`\http://<ip_address>/api/ui`

+
您必须使用 Deploy 虚拟机的 IP 地址。

. 单击 *Mediator*，然后单击 *GET /mediators*。
. 单击“尝试一下！”以显示由 Deploy 维护的中介器列表。
+
记下所需中介实例的 ID。

. 单击“*Mediator*”，然后单击“*POST*”。
. 提供 mediator_id 的值。
. 单击旁边的“模型”  `iscsi_target`并完成名称值。
+
使用目标名称作为 iqn_name 参数。

. 单击“试用！”来创建中介 iSCSI 目标。
+
如果请求成功，您将收到 HTTP 状态代码 200。

. 如果新 Deploy 虚拟机的 IP 地址与原始 Deploy 虚拟机不同，则必须使用ONTAP CLI 删除旧的调解器 iSCSI 目标并添加新的目标：
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
这 `<ip_address>`参数是新的 Deploy 虚拟机的 IP 地址。



这些命令允许ONTAP Select节点发现新 Deploy 实用程序虚拟机上的邮箱磁盘。

. 确定中介磁盘的名称：
+
`disk show -container-type mediator`

. 将邮箱磁盘分配给两个节点：
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. 验证存储故障转移是否已启用：
+
`storage failover show`



.完成后
如果使用容量池许可，则必须重新安装每个容量池许可证。有关更多详细信息，请参阅重新安装容量池许可证。

.相关信息
* link:task_install_deploy.html["安装ONTAP Select Deploy"]
* link:task_cli_migrate_deploy.html#restoring-the-deploy-configuration-data-to-the-new-virtual-machine["将 Deploy 配置数据还原到新的虚拟机"]
* link:task_adm_licenses.html#reinstalling-a-capacity-pool-license["重新安装容量池许可证"]

